### ISSUE TITLE
ImportError: cannot import name '__version__' from 'csi_crypt' (unknown location)

### ISSUE THREAD

**Issue by Lykos153** [Lykos153/csi-crypt#9]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/appdir/csi_crypt/run.py", line 13, in <module>
    from .identityserver import IdentityServer
  File "/appdir/csi_crypt/identityserver.py", line 9, in <module>
    from . import __version__ as DRIVER_VERSION
ImportError: cannot import name '__version__' from 'csi_crypt' (unknown location)
```

**Comment by Lykos153** [comment]
https://github.com/jwodder/versioningit
https://pypi.org/project/dunamai/
